name: impact_zone
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  device_info_plus: ^11.0.0
  fluttertoast: ^8.2.7
  connectivity_plus: ^6.0.4
  package_info_plus: ^8.0.3
  dio: ^5.7.0
  logger: ^2.4.0
  get_storage: ^2.1.1
  smooth_page_indicator: ^1.2.0+3
  colorful_safe_area: ^1.0.0
  country_picker: ^2.0.27
  dropdown_button2: ^2.3.9
  fancy_shimmer_image: ^2.0.3
  pinput: ^5.0.0
  intl: ^0.19.0
  flutter_easyloading: ^3.0.5
  syncfusion_flutter_barcodes: ^29.1.33
  shimmer: ^3.0.0
  dotted_line: ^3.2.3
  permission_handler: ^12.0.0+1
  file_picker: ^10.1.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/font/
    - assets/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/font/Satoshi-Bold.otf
          weight: 700
        - asset: assets/font/Satoshi-Medium.otf
          weight: 600
        - asset: assets/font/Satoshi-Regular.otf
          weight: 500
        - asset: assets/font/Satoshi-Light.otf
          weight: 400

