class AppImages {
  AppImages._();

  static const String iconsAppLogo = 'assets/icons/app_logo.png';
  static const String iconsAppointment = 'assets/icons/appointment.png';
  static const String iconsBack = 'assets/icons/back.png';
  static const String iconsCalendarSelected = 'assets/icons/calendar_selected.png';
  static const String iconsCalendarUnselected = 'assets/icons/calendar_unselected.png';
  static const String iconsCall = 'assets/icons/call.png';
  static const String iconsChatSelected = 'assets/icons/chat_selected.png';
  static const String iconsChatUnselected = 'assets/icons/chat_unselected.png';
  static const String iconsCheckIn = 'assets/icons/check_in.png';
  static const String iconsClassAppointment = 'assets/icons/class_appointment.png';
  static const String iconsClassSchedule = 'assets/icons/class_schedule.png';
  static const String iconsCrown = 'assets/icons/crown.png';
  static const String iconsDate = 'assets/icons/date.png';
  static const String iconsDrawerMembers = 'assets/icons/drawer_members.png';
  static const String iconsEmail = 'assets/icons/email.png';
  static const String iconsHidePassword = 'assets/icons/hide_password.png';
  static const String iconsHomeBg = 'assets/icons/home_bg.jpg';
  static const String iconsHomeSelected = 'assets/icons/home_selected.png';
  static const String iconsHomeUnselected = 'assets/icons/home_unselected.png';
  static const String iconsLocation = 'assets/icons/location.png';
  static const String iconsLogOut = 'assets/icons/log_out.png';
  static const String iconsMenu = 'assets/icons/menu.png';
  static const String iconsNotification = 'assets/icons/notification.png';
  static const String iconsPOS = 'assets/icons/POS.png';
  static const String iconsPassword = 'assets/icons/password.png';
  static const String iconsPasswordChanged = 'assets/icons/password_changed.png';
  static const String iconsProfileImage = 'assets/icons/profile_image.png';
  static const String iconsProfileSelected = 'assets/icons/profile_selected.png';
  static const String iconsProfileUnselected = 'assets/icons/profile_unselected.png';
  static const String iconsReport = 'assets/icons/report.png';
  static const String iconsShowPassword = 'assets/icons/show_password.png';
  static const String iconsSms = 'assets/icons/sms.png';
  static const String iconsTask = 'assets/icons/task.png';
  static const String iconsTime = 'assets/icons/time.png';
  static const String iconsTraining = 'assets/icons/training.png';
  static const String iconsFilter = 'assets/icons/filter.png';
  static const String iconsSearch = 'assets/icons/search.png';
  static const String iconsBell = 'assets/icons/bell.png';
  static const String iconsCompleteTodo = 'assets/icons/tick-circle.png';
  static const String iconsUnCheckTodo = 'assets/icons/un_tick_circle.png';
  static const String iconsBookmark = 'assets/icons/vector.png';
  static const String iconsEmptyBookmark = 'assets/icons/empty_vector.png';
  static const String iconsProduct = 'assets/icons/product.png';
  static const String iconsAgreements= 'assets/icons/agreements.png';
  static const String iconsService= 'assets/icons/services.png';
  static const String iconsDropDownUser= 'assets/icons/drop_down_user.png';
  static const String iconsDropDownIcon= 'assets/icons/drop_down_icon.png';
  static const String iconsDiscountIcon= 'assets/icons/discount_icon.png';
  static const String iconsCashIcon= 'assets/icons/cash.png';
  static const String iconsCheckIcon= 'assets/icons/check.png';
  static const String iconsCardOnFileIcon= 'assets/icons/card_on_file.png';
  static const String iconsPrePayIcon= 'assets/icons/pre_pay.png';
  static const String iconsCreditCardIcon= 'assets/icons/credit_card.png';
  static const String iconsRewardIcon= 'assets/icons/reward.png';
  static const String iconsPayLaterIcon= 'assets/icons/pay_later.png';
  static const String iconsVisaIcon= 'assets/icons/visa.png';
  static const String iconsAddNewCardIcon= 'assets/icons/add_new_card.png';
  static const String iconsSingleUserIcon= 'assets/icons/single_user.png';
  static const String iconsCardIcon= 'assets/icons/card.png';
  static const String iconsCvvIcon= 'assets/icons/cvv.png';
  static const String iconsActiveIcon= 'assets/icons/active.png';
  static const String iconsThreeDotIcon= 'assets/icons/three_dot.png';
  static const String iconsAttachmentIcon= 'assets/icons/attachment.png';
  static const String iconsSendIcon= 'assets/icons/send.png';
  static const String iconsMediaIcon= 'assets/icons/media.png';
  static const String iconsCameraIcon= 'assets/icons/camera.png';
  static const String iconsDocsIcon= 'assets/icons/docs.png';
  static const String iconsPdfIcon= 'assets/icons/pdf_icon.png';
  static const String iconsDeActiveIcon= 'assets/icons/de_active.png';


  static const String imagesAuthBg = 'assets/images/auth_bg.png';
  static const String imagesOnBoarding1 = 'assets/images/on_boarding1.png';
  static const String imagesOnBoarding2 = 'assets/images/on_boarding2.png';
  static const String imagesOnBoarding3 = 'assets/images/on_boarding3.png';
  static const String imagesSplashLogo = 'assets/images/splash_logo.png';


}
